export const Site = {
  name: "Rf Technologies",
  logo: "https://res.cloudinary.com/dzmrdbwqh/image/upload/v1703166464/RF%20Technologies%20Logo-20231221T134528Z-001/RF%20Technologies%20Logo/Side%20by%20Side/PNG/Side_Logo-05_mjeold.png",
  WhiteLogo:
    "https://res.cloudinary.com/dzmrdbwqh/image/upload/v1719825111/RfTechnologiesWebsite/Side_Logo-02_2_izjlvf.png",
  logoWhite: "",
  url: "https://rftechnologies.com.pk",
  placeholder:
    "https://res.cloudinary.com/dzmrdbwqh/image/upload/v1721470809/RfTechnologiesWebsite/360_F_517535712_q7f9QC9X6TQxWi6xYZZbMmw5cnLMr279_e7mp3b.jpg",
  mapAddress:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11672.945750644447!2d-122.42107853750231!3d37.7730507907087!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80858070cc2fbd55%3A0xa71491d736f62d5c!2sGolden%20Gate%20Bridge!5e0!3m2!1sen!2sus!4v1619524992238!5m2!1sen!2sus",
  address: "3rd floor Taha Mall, Defence Rd, Rawalpindi, Punjab 47300",
  email: "info@rftechnologies.com.pk",
  number: "+92 334 4738506",
  themeColor: "#002475",
  social_links: {
    facebook: "https://www.facebook.com/rftechnologiespk/",
    twitter: "https://twitter.com/rftechnologies_",
    instagram: "https://www.instagram.com/rftechnologiespk/",
    linkdin: "https://www.facebook.com/rftechnologiespk/",
    youtube: "https://www.youtube.com/channel/UCwNKTsriLX7-VB_KLG5-vUQ",
    whatsapp: "https://api.whatsapp.com/send?phone=+923344738506%E2%80%8B",
  },
  SEO_prefix: "RF Technologies",
  SEO_title: "RF Technologies | Digital Product, Commerce & Technology Partner",
  SEO_Description:
    "RF Technologies solves business problems using technology through Shopify engineering, product and SaaS development, custom software, and long-term technology partnership.",
  routes: [
    { id: 1, name: "Home", link: "" },
    { id: 2, name: "Solutions", link: "/solutions" },
    { id: 3, name: "Shopify Engineering", link: "/solutions/shopify-engineering" },
    {
      id: 4,
      name: "Product & SaaS Development",
      link: "/solutions/product-saas-development",
    },
    { id: 5, name: "Custom Software", link: "/solutions/custom-software" },
    {
      id: 6,
      name: "Technology Partnership",
      link: "/solutions/technology-partnership",
    },
    { id: 7, name: "Products", link: "/products" },
    { id: 8, name: "BlueTicks", link: "/products/blueticks" },
    { id: 9, name: "Spotlyy", link: "/spotlyy" },
    { id: 10, name: "Work", link: "/our-work" },
    { id: 11, name: "Industries", link: "/industries" },
    { id: 12, name: "eCommerce", link: "/industries/ecommerce" },
    { id: 13, name: "Startups", link: "/industries/startups" },
    { id: 14, name: "SMEs", link: "/industries/smes" },
    { id: 15, name: "Agencies", link: "/industries/agencies" },
    { id: 16, name: "Insights", link: "/blogs" },
    { id: 17, name: "Resources", link: "/faq" },
    { id: 18, name: "About", link: "/about-us" },
    { id: 19, name: "Contact", link: "/contact-us" },
  ],
};
