import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/context/ThemeContext";
import { Advent_Pro } from "next/font/google";
import { Nunito } from "next/font/google";
export const nunito = Nunito({ subsets: ["latin"], variable: "--font-nunito" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const advent_Pro = Advent_Pro({
  subsets: ["latin"],
  variable: "--font-advent-pro",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/png"
          sizes="32x32"
        />
      </head>
      <body className={`${advent_Pro.variable} ${nunito.variable}`}>
        <ThemeProvider>
          <Header />
          <main className="bg-light">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
